services:
  api:
    build:
      context: .
      target: prod
    ports:
      - "3500:8000" # see docs/PORTS.md
    volumes:
      - finance-db:/root/.finance
    environment:
      FINANCE_DEBUG: "false"
      FINANCE_PORT: "8000"
      FINANCE_DB_URL: ""
      CORS_ORIGINS: "http://localhost:3502"
    restart: always

  web:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3502:80" # see docs/PORTS.md
    depends_on:
      - api
    restart: always

volumes:
  finance-db:
